spring:
  datasource:
    url: jdbc:postgresql://dpg-d7r4kdpj2pic73f4eah0-a:5432/mazdoor_database
    username: mazdoor_user
    password: twIvtq1POLpyZJLg5QDCXzwHNYj0mJjy
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true