spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mazdoor_database
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

